### ISSUE TITLE
Device ID doesn't update before you once open visualization

### ISSUE THREAD

**Issue by ktkarhu** [aalto-trafficsense/regular-routes-client#28]

**Comment by jannesuo** [comment]
I think that device id updates only when resuming the application. Anyways, after implementing authentication, "device id" is going to be obsolete/removed as such -> no fix.

Ps. You can get your id (number) for visualizing by checking the url when you press "visualize" and open it in browser.

**Comment by jannesuo** [comment]
I noticed that I had put a 'force update' to device id -field that occurs when opening visualization. The other place for update is the onResume() -method that was the original timing for update. 

When I get the authentication feature working, the UI will show device id (number) already in the ui instead of some uuid. Also devices-api will be removed and device id query will use only device-api that return single device id but requires authentication + session_token to work.
